set -g mouse on
set -g pane-border-style "fg=#3c3836,bg=#3c3836"
set -g pane-active-border-style "fg=#fb4934,bg=#fb4934,bold"
set -g pane-border-lines heavy
set -g pane-border-indicators both
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[fg=#282828#,bg=#fb4934#,bold]  #P: #{pane_current_command} ,#[fg=#a89984#,bg=#3c3836]  #P: #{pane_current_command} }"
set -g history-limit 50000
set -s escape-time 10
set -g renumber-windows on
bind c new-window -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Config reloaded"
